Lambda School Data Science

*Unit 2, Sprint 3, Module 1*

---


# Define ML problems

You will use your portfolio project dataset for all assignments this sprint.

## Assignment

Complete these tasks for your project, and document your decisions.

- [ ] Choose your target. Which column in your tabular dataset will you predict?
- [ ] Is your problem regression or classification?
- [ ] How is your target distributed?
    - Classification: How many classes? Are the classes imbalanced?
    - Regression: Is the target right-skewed? If so, you may want to log transform the target.
- [ ] Choose your evaluation metric(s).
    - Classification: Is your majority class frequency >= 50% and < 70% ? If so, you can just use accuracy if you want. Outside that range, accuracy could be misleading. What evaluation metric will you choose, in addition to or instead of accuracy?
    - Regression: Will you use mean absolute error, root mean squared error, R^2, or other regression metrics?
- [ ] Choose which observations you will use to train, validate, and test your model.
    - Are some observations outliers? Will you exclude them?
    - Will you do a random split or a time-based split?
- [ ] Begin to clean and explore your data.
- [ ] Begin to choose which features, if any, to exclude. Would some features "leak" future information?

If you haven't found a dataset yet, do that today. [Review requirements for your portfolio project](https://lambdaschool.github.io/ds/unit2) and choose your dataset.

Some students worry, ***what if my model isn't “good”?*** Then, [produce a detailed tribute to your wrongness. That is science!](https://twitter.com/nathanwpyle/status/1176860147223867393)

In [0]:
import pandas as pd

In [0]:
path = '/berrios.csv'

In [8]:
df = pd.read_csv(path)
df.head()

  pitch_type   game_date  ...  if_fielding_alignment  of_fielding_alignment
0         FF  2018-09-28  ...               Standard               Standard
1         CU  2018-09-28  ...               Standard               Standard
2         CU  2018-09-28  ...               Standard               Standard
3         FF  2018-09-28  ...               Standard               Standard
4         CU  2018-09-28  ...               Standard               Standard

[5 rows x 89 columns]

In [10]:
df['pitch_name'].value_counts(normalize=True)

4-Seam Fastball    0.343949
Curveball          0.304392
2-Seam Fastball    0.260476
Changeup           0.090848
Pitch Out          0.000335
Name: pitch_name, dtype: float64

- **Target:** pitch_name
- This is a **classification** problem
- For this pitcher, there are 4 primary classes, but there are different pitch classifications for different pitchers. These combinations are usually imbalanced. In this case, the pitch type of "Pitch Out" I may choose to consider as an outlier, as this is only thrown as a response to runners on base, and is not a pitch intended for the batter.
- For this project, a baseline of the most common pitch type, and an accuracy evaluation metric seems appropriate.
- For the train/test/validate split, I will use a time-based split. I was thinking taking training data from 2015-2017, validation data from 2018, and testing data from 2019. However, as pitching strategies have likely changed over time, the testing/validation data may have variance not accounted for in the training set. I need to research this further.
- Useful features: batter, pitcher, stance, ball/strike, count, number of pitches, some combination of previous pitches (needs to be engineered).